In [1]:
import pandas as pd

In [2]:
annos = pd.read_csv('annotations.csv')

In [3]:
annos

               file_name  width  height  x1  y1   x2   y2  category
0           000_0001.png    134     128  19   7  120  117         0
1           000_0002.png    165     151  23  12  149  138         0
2           000_0003.png    128     122  22  14  116  105         0
3           000_0010.png     80      73  14   8   67   63         0
4           000_0011.png    186     174  36  15  155  157         0
...                  ...    ...     ...  ..  ..  ...  ...       ...
6159  056_1_0018_1_j.png    122      94  25  20   80   79        56
6160  056_1_0019_1_j.png    224     207  39  39  188  178        56
6161  056_1_0020_1_j.png    128     115  32  30   89   79        56
6162  057_1_0001_1_j.png    100      95  21  22   74   75        57
6163  057_1_0002_1_j.png    145     136  28  25  111  114        57

[6164 rows x 8 columns]

In [8]:
filename = '000_0001.png'
rs = annos.query("file_name == '000_0001.png'")

In [27]:
type(rs.iloc[0]['width'])

numpy.int64